modules:
  Permissions:
    enabled: true
    dependencies: []
  Morpheus:
    enabled: true
    dependencies:
      - Permissions
    percentage: 50.0
    enterBedMessage: $1 hat sich ins Bett gelegt ($2)
    leaveBedMessage: $1 ist aufgestanden ($2)
    sleepSuccessMessage: Der Schlaf tat gut, auf ein neues!
  Colors:
    enabled: true
    dependencies: []
  Lock:
    enabled: true
    dependencies: []
  Vanish:
    enabled: true
    dependencies: []
  gp:
    Afk:
      enabled: true
      dependencies: []