name: JRKPlugin
description: Multifunktionsplugin des JRK-Servers
version: 1.0.0
author: RagingLightning
main: de.r13g.jrkniedersachsen.plugin.Plugin
api-version: 1.16
commands:
  jrkadmin:
    usage: /jrkadmin
    description: TBD
    permission: jrk.admin
  jrk:
    usage: /jrk
    description: TBD
    permission: jrk.gp
  morpheus:
    usage: /morpheus <option> <value>
    description: Einstellungen des Morpheus-Moduls verändern
    permission: jrk.morpheus.admin
  colors:
    usage: /colors <option> <value>
    description: Einstellungen des Colors-Moduls verändern
    permission: jrk.colors.admin
permissions:
  jrk.gp:
    description: Gibt dem Spieler die Rechte, GP Commands zu nutzen
    default: true
  jrk.gp.*:
    description: Gibt dem Spieler die Rechte, alle GP Commands zu nutzen
    default: true
    children:
      jrk.gp: true
      jrk.gp.tps: true
  jrk.gp.tps:
    description: Gibt dem Spieler die Rechte, den GP Command tps zu nutzen
    default: true
  jrk.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am JRK-Plugin vorzunehmen.
    default: op
    children:
      jrk.morpheus.admin: true
      jrk.colors.admin: true
  jrk.morpheus.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am Morpheus-Modul vorzunehmen.
    default: op
  jrk.morpheus.bypass:
    description: Der Spieler wird bei der Schlaf-Vote-Funktion ignoriert.
    default: op
  jrk.colors.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am Morpheus-Modul vorzunehmen.
    default: op