name: JRKPlugin
description: Multifunktionsplugin des JRK-Servers
version: 1.5.0
author: RagingLightning
main: de.r13g.jrkniedersachsen.plugin.Plugin
api-version: 1.16
commands:
  jrkadmin:
    usage: /jrkadmin
    description: TBD
    permission: jrk.admin
  jrk:
    usage: /jrk
    description: TBD
    permission: jrk.gp
  morpheus:
    usage: /morpheus <option> <value>
    description: Einstellungen des Morpheus-Moduls verändern
    permission: jrk.morpheus.admin
  colors:
    usage: /colors <option> <value>
    description: Einstellungen des Colors-Moduls verändern
    permission: jrk.colors.admin
  lock:
    usage: /lock <option> <password>
  vanish:
    usage: /vanish
    permission: jrk.vanish
  invsee:
    usage: /invsee <"player"|"chest"> <player>
    permission: jrk.invsee
permissions:
  jrk.gp:
    description: Gibt dem Spieler die Rechte, GP Commands zu nutzen
  jrk.gp.*:
    description: Gibt dem Spieler die Rechte, alle GP Commands zu nutzen
    default: true
    children:
      jrk.gp: true
      jrk.gp.tps: true
      jrk.gp.afk: true
      jrk.gp.pigseat: true
  jrk.gp.tps:
    description: Gibt dem Spieler die Rechte, den GP Command tps zu nutzen
    default: true
    children:
      bukkit.command.tps: true
  jrk.gp.afk:
    description: Gibt dem Spieler die Rechte, den GP Command afk zu nutzen
    default: true
  jrk.gp.pigseat:
    description: Gibt dem Spieler die Rechte, den GP Command pigseat zu nutzen
    default: true
  jrk.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen an allen Modulen des JRK-Plugins vorzunehmen.
    default: op
    children:
      jrk.morpheus.admin: true
      jrk.colors.admin: true
      jrk.lock.admin: true
  jrk.morpheus.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am Morpheus-Modul vorzunehmen.
  jrk.morpheus.bypass:
    description: Der Spieler wird bei der Schlaf-Vote-Funktion ignoriert.
  jrk.colors.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am Colors-Modul vorzunehmen.
  jrk.lock.create:
    description: Gibt dem Spieler die Rechte, Locks zu erstellen.
    default: true
  jrk.lock.bypass:
    description: Der Spieler kann alle Locks umgehen
  jrk.lock.admin:
    description: Gibt dem Spieler die Rechte, alle Locks aufzulisten
  jrk.vanish:
    description: Gibt dem Spieler die Rechte, unsichtbar zu werden
  jrk.invsee:
    description: Gibd dem Spieler die Rechte, Inventare anderer Spieler zu sehen