modules:
  morpheus:
    enabled: true
    percentage: 50.0
    enterBedMessage: $1 hat sich ins Bett gelegt $2
    leaveBedMessage: $1 ist aufgestanden $2
    sleepSuccessMessage: Der Schlaf tat gut, auf ein neues!