name: JRKPlugin
description: Multifunktionsplugin des JRK-Servers
version: 1.0.0
author: RagingLightning
main: de.r13g.jrkniedersachsen.plugin.Plugin
api-version: 1.16
commands:
  jrkadmin:
    usage: /jrkadmin
    description: TBD
    permission: jrk.admin
  jrk:
    usage: /jrk
    description: TBD
  morpheus:
    usage: /morpheus <option> <value>
    description: Einstellungen des Morpheus-Moduls verändern
    permission: jrk.morpheus.admin
permissions:
  jrk.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am JRK-Plugin vorzunehmen.
    default: op
    children:
      jrk.morpheus.admin: true
  jrk.morpheus.admin:
    description: Gibt dem Spieler die Rechte, Einstellungen am Morpheus-Modul vorzunehmen.
    default: op
  jrk.morpheus.bypass:
    description: Der Spieler wird bei der Schlaf-Vote-Funktion ignoriert.
    default: op